# Generated by Django 4.2.7 on 2023-12-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0002_complaint_alter_patient_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='insurance_provider',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='payment_method',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='preferred_language',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='reason_for_visit',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='referring_physician',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='religious_preferences',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
